### ISSUE TITLE
CMag is always empty after loading data via "New star from AAVSO Database..."

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#47] opened 2020-08-23 18:15 UTC
CMag is always empty after loading data via "New star from AAVSO Database...": see attached picture for details
![image](https://user-images.githubusercontent.com/44919945/90985596-af23ee00-e585-11ea-9946-306e59bbe73c.png)

**Comment by dbenn** [comment] 2020-08-23 22:51
Confirmed. Download format file data for N Cas 2020 contains CMag.

I wonder when this error crept in? May always have been there since the web service AID reader was implemented and not picked up.

Fix committed.

**Comment by mpyat2** [comment] 2020-08-24 06:38
Thank you, @dbenn , it works!
Remark: why Cmag is important: in the case were one comp-star is used (non-ensemble), both Kmag and Cmag are instrumental magnitudes, so Cmag is needed to get apparent check-star magnitude (to estimate the quality of photometry).

**Comment by dbenn** [comment] 2020-09-26 04:46
fixed indent in AID retriever after addition of cMag handling; closing

**Closed by dbenn** 2020-09-26 04:46 UTC
Labels: bug
