### ISSUE TITLE
Plugin to correct magnitudes for light contamination from companions

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#344] opened 2023-03-29 08:35 UTC
Make a "deblending" plug-in using a simple approach described in the VSX manual:
https://www.aavso.org/vsx/_images/Manual.pdf [https://www.aavso.org/vsx/_images/COMBLEND.xlsx]

This topic once caused a heated debate on the VStar forum (cannot find the forum branch, unfortunately). I am not pretending to make the ultimate solution (with requires considering many fine things), only an implementation of the existing recommendations found in the VSX manual.

**Comment by dbenn** [comment] 2023-03-30 04:34
Is this a duplicate of #147 @mpyat2 ?

**Comment by mpyat2** [comment] 2023-03-31 11:52
Oh, yes, @dbenn , you are right.

**Comment by mpyat2** [comment] 2023-03-31 11:52
Duplicates #147

**Closed** 2023-03-31 11:52 UTC
Labels: plug-in
